spring:
  application:
    name: gateway
  profiles:
    default: eureka-on
server:
  port: 4040
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true